/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthenticatedAutomationsIndexRouteImport } from './routes/_authenticated/automations/index'
import { Route as AuthenticatedAutomationsAutomationIdRouteRouteImport } from './routes/_authenticated/automations/$automationId/route'
import { Route as AuthenticatedConversationsIndexRouteImport } from './routes/_authenticated/conversations/index'
import { Route as AuthenticatedConversationsConversationIdRouteImport } from './routes/_authenticated/conversations/$conversationId'
import { Route as AuthenticatedAutomationsAutomationIdIndexRouteImport } from './routes/_authenticated/automations/$automationId/index'
import { Route as AuthenticatedAutomationsAutomationIdActivityRouteImport } from './routes/_authenticated/automations/$automationId/activity'
import { Route as AuthenticatedAutomationsAutomationIdContentRouteImport } from './routes/_authenticated/automations/$automationId/content'
import { Route as AuthenticatedAutomationsAutomationIdDirectMessageRouteImport } from './routes/_authenticated/automations/$automationId/direct-message'
import { Route as AuthenticatedAutomationsAutomationIdFinalActionRouteImport } from './routes/_authenticated/automations/$automationId/final-action'
import { Route as AuthenticatedAutomationsAutomationIdIdentificationRouteImport } from './routes/_authenticated/automations/$automationId/identification'
import { Route as AuthenticatedAutomationsAutomationIdKeywordRouteImport } from './routes/_authenticated/automations/$automationId/keyword'
import { Route as AuthenticatedAutomationsAutomationIdPublicReplyRouteImport } from './routes/_authenticated/automations/$automationId/public-reply'
import { Route as AuthenticatedAutomationsAutomationIdReviewRouteImport } from './routes/_authenticated/automations/$automationId/review'
import { Route as AuthenticatedAutomationsAutomationIdTestRouteImport } from './routes/_authenticated/automations/$automationId/test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAutomationsIndexRoute =
  AuthenticatedAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdRouteRoute =
  AuthenticatedAutomationsAutomationIdRouteRouteImport.update({
    id: '/automations/$automationId',
    path: '/automations/$automationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationsIndexRoute =
  AuthenticatedConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationsConversationIdRoute =
  AuthenticatedConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdIndexRoute =
  AuthenticatedAutomationsAutomationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAutomationsAutomationIdRouteRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdActivityRoute =
  AuthenticatedAutomationsAutomationIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAutomationsAutomationIdRouteRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdContentRoute =
  AuthenticatedAutomationsAutomationIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAutomationsAutomationIdRouteRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdDirectMessageRoute =
  AuthenticatedAutomationsAutomationIdDirectMessageRouteImport.update({
    id: '/direct-message',
    path: '/direct-message',
    getParentRoute: () => AuthenticatedAutomationsAutomationIdRouteRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdFinalActionRoute =
  AuthenticatedAutomationsAutomationIdFinalActionRouteImport.update({
    id: '/final-action',
    path: '/final-action',
    getParentRoute: () => AuthenticatedAutomationsAutomationIdRouteRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdIdentificationRoute =
  AuthenticatedAutomationsAutomationIdIdentificationRouteImport.update({
    id: '/identification',
    path: '/identification',
    getParentRoute: () => AuthenticatedAutomationsAutomationIdRouteRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdKeywordRoute =
  AuthenticatedAutomationsAutomationIdKeywordRouteImport.update({
    id: '/keyword',
    path: '/keyword',
    getParentRoute: () => AuthenticatedAutomationsAutomationIdRouteRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdPublicReplyRoute =
  AuthenticatedAutomationsAutomationIdPublicReplyRouteImport.update({
    id: '/public-reply',
    path: '/public-reply',
    getParentRoute: () => AuthenticatedAutomationsAutomationIdRouteRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdReviewRoute =
  AuthenticatedAutomationsAutomationIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAutomationsAutomationIdRouteRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdTestRoute =
  AuthenticatedAutomationsAutomationIdTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => AuthenticatedAutomationsAutomationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/automations/$automationId': typeof AuthenticatedAutomationsAutomationIdRouteRouteWithChildren
  '/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/automations/$automationId/activity': typeof AuthenticatedAutomationsAutomationIdActivityRoute
  '/automations/$automationId/content': typeof AuthenticatedAutomationsAutomationIdContentRoute
  '/automations/$automationId/direct-message': typeof AuthenticatedAutomationsAutomationIdDirectMessageRoute
  '/automations/$automationId/final-action': typeof AuthenticatedAutomationsAutomationIdFinalActionRoute
  '/automations/$automationId/identification': typeof AuthenticatedAutomationsAutomationIdIdentificationRoute
  '/automations/$automationId/keyword': typeof AuthenticatedAutomationsAutomationIdKeywordRoute
  '/automations/$automationId/public-reply': typeof AuthenticatedAutomationsAutomationIdPublicReplyRoute
  '/automations/$automationId/review': typeof AuthenticatedAutomationsAutomationIdReviewRoute
  '/automations/$automationId/test': typeof AuthenticatedAutomationsAutomationIdTestRoute
  '/automations/$automationId/': typeof AuthenticatedAutomationsAutomationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/automations': typeof AuthenticatedAutomationsIndexRoute
  '/conversations': typeof AuthenticatedConversationsIndexRoute
  '/automations/$automationId/activity': typeof AuthenticatedAutomationsAutomationIdActivityRoute
  '/automations/$automationId/content': typeof AuthenticatedAutomationsAutomationIdContentRoute
  '/automations/$automationId/direct-message': typeof AuthenticatedAutomationsAutomationIdDirectMessageRoute
  '/automations/$automationId/final-action': typeof AuthenticatedAutomationsAutomationIdFinalActionRoute
  '/automations/$automationId/identification': typeof AuthenticatedAutomationsAutomationIdIdentificationRoute
  '/automations/$automationId/keyword': typeof AuthenticatedAutomationsAutomationIdKeywordRoute
  '/automations/$automationId/public-reply': typeof AuthenticatedAutomationsAutomationIdPublicReplyRoute
  '/automations/$automationId/review': typeof AuthenticatedAutomationsAutomationIdReviewRoute
  '/automations/$automationId/test': typeof AuthenticatedAutomationsAutomationIdTestRoute
  '/automations/$automationId': typeof AuthenticatedAutomationsAutomationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_authenticated/automations/$automationId': typeof AuthenticatedAutomationsAutomationIdRouteRouteWithChildren
  '/_authenticated/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/_authenticated/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/_authenticated/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/_authenticated/automations/$automationId/activity': typeof AuthenticatedAutomationsAutomationIdActivityRoute
  '/_authenticated/automations/$automationId/content': typeof AuthenticatedAutomationsAutomationIdContentRoute
  '/_authenticated/automations/$automationId/direct-message': typeof AuthenticatedAutomationsAutomationIdDirectMessageRoute
  '/_authenticated/automations/$automationId/final-action': typeof AuthenticatedAutomationsAutomationIdFinalActionRoute
  '/_authenticated/automations/$automationId/identification': typeof AuthenticatedAutomationsAutomationIdIdentificationRoute
  '/_authenticated/automations/$automationId/keyword': typeof AuthenticatedAutomationsAutomationIdKeywordRoute
  '/_authenticated/automations/$automationId/public-reply': typeof AuthenticatedAutomationsAutomationIdPublicReplyRoute
  '/_authenticated/automations/$automationId/review': typeof AuthenticatedAutomationsAutomationIdReviewRoute
  '/_authenticated/automations/$automationId/test': typeof AuthenticatedAutomationsAutomationIdTestRoute
  '/_authenticated/automations/$automationId/': typeof AuthenticatedAutomationsAutomationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accept-invitation'
    | '/contacts'
    | '/leads'
    | '/users'
    | '/workspace'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/automations/$automationId'
    | '/conversations/$conversationId'
    | '/automations/'
    | '/conversations/'
    | '/automations/$automationId/activity'
    | '/automations/$automationId/content'
    | '/automations/$automationId/direct-message'
    | '/automations/$automationId/final-action'
    | '/automations/$automationId/identification'
    | '/automations/$automationId/keyword'
    | '/automations/$automationId/public-reply'
    | '/automations/$automationId/review'
    | '/automations/$automationId/test'
    | '/automations/$automationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accept-invitation'
    | '/contacts'
    | '/leads'
    | '/users'
    | '/workspace'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/conversations/$conversationId'
    | '/automations'
    | '/conversations'
    | '/automations/$automationId/activity'
    | '/automations/$automationId/content'
    | '/automations/$automationId/direct-message'
    | '/automations/$automationId/final-action'
    | '/automations/$automationId/identification'
    | '/automations/$automationId/keyword'
    | '/automations/$automationId/public-reply'
    | '/automations/$automationId/review'
    | '/automations/$automationId/test'
    | '/automations/$automationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/accept-invitation'
    | '/_authenticated/contacts'
    | '/_authenticated/leads'
    | '/_authenticated/users'
    | '/_authenticated/workspace'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/_authenticated/automations/$automationId'
    | '/_authenticated/conversations/$conversationId'
    | '/_authenticated/automations/'
    | '/_authenticated/conversations/'
    | '/_authenticated/automations/$automationId/activity'
    | '/_authenticated/automations/$automationId/content'
    | '/_authenticated/automations/$automationId/direct-message'
    | '/_authenticated/automations/$automationId/final-action'
    | '/_authenticated/automations/$automationId/identification'
    | '/_authenticated/automations/$automationId/keyword'
    | '/_authenticated/automations/$automationId/public-reply'
    | '/_authenticated/automations/$automationId/review'
    | '/_authenticated/automations/$automationId/test'
    | '/_authenticated/automations/$automationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/automations/': {
      id: '/_authenticated/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AuthenticatedAutomationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations/$automationId': {
      id: '/_authenticated/automations/$automationId'
      path: '/automations/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations/': {
      id: '/_authenticated/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AuthenticatedConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations/$conversationId': {
      id: '/_authenticated/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof AuthenticatedConversationsConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations/$automationId/': {
      id: '/_authenticated/automations/$automationId/'
      path: '/'
      fullPath: '/automations/$automationId/'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdIndexRouteImport
      parentRoute: typeof AuthenticatedAutomationsAutomationIdRouteRoute
    }
    '/_authenticated/automations/$automationId/activity': {
      id: '/_authenticated/automations/$automationId/activity'
      path: '/activity'
      fullPath: '/automations/$automationId/activity'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdActivityRouteImport
      parentRoute: typeof AuthenticatedAutomationsAutomationIdRouteRoute
    }
    '/_authenticated/automations/$automationId/content': {
      id: '/_authenticated/automations/$automationId/content'
      path: '/content'
      fullPath: '/automations/$automationId/content'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdContentRouteImport
      parentRoute: typeof AuthenticatedAutomationsAutomationIdRouteRoute
    }
    '/_authenticated/automations/$automationId/direct-message': {
      id: '/_authenticated/automations/$automationId/direct-message'
      path: '/direct-message'
      fullPath: '/automations/$automationId/direct-message'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdDirectMessageRouteImport
      parentRoute: typeof AuthenticatedAutomationsAutomationIdRouteRoute
    }
    '/_authenticated/automations/$automationId/final-action': {
      id: '/_authenticated/automations/$automationId/final-action'
      path: '/final-action'
      fullPath: '/automations/$automationId/final-action'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdFinalActionRouteImport
      parentRoute: typeof AuthenticatedAutomationsAutomationIdRouteRoute
    }
    '/_authenticated/automations/$automationId/identification': {
      id: '/_authenticated/automations/$automationId/identification'
      path: '/identification'
      fullPath: '/automations/$automationId/identification'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdIdentificationRouteImport
      parentRoute: typeof AuthenticatedAutomationsAutomationIdRouteRoute
    }
    '/_authenticated/automations/$automationId/keyword': {
      id: '/_authenticated/automations/$automationId/keyword'
      path: '/keyword'
      fullPath: '/automations/$automationId/keyword'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdKeywordRouteImport
      parentRoute: typeof AuthenticatedAutomationsAutomationIdRouteRoute
    }
    '/_authenticated/automations/$automationId/public-reply': {
      id: '/_authenticated/automations/$automationId/public-reply'
      path: '/public-reply'
      fullPath: '/automations/$automationId/public-reply'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdPublicReplyRouteImport
      parentRoute: typeof AuthenticatedAutomationsAutomationIdRouteRoute
    }
    '/_authenticated/automations/$automationId/review': {
      id: '/_authenticated/automations/$automationId/review'
      path: '/review'
      fullPath: '/automations/$automationId/review'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdReviewRouteImport
      parentRoute: typeof AuthenticatedAutomationsAutomationIdRouteRoute
    }
    '/_authenticated/automations/$automationId/test': {
      id: '/_authenticated/automations/$automationId/test'
      path: '/test'
      fullPath: '/automations/$automationId/test'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdTestRouteImport
      parentRoute: typeof AuthenticatedAutomationsAutomationIdRouteRoute
    }
  }
}

interface AuthenticatedAutomationsAutomationIdRouteRouteChildren {
  AuthenticatedAutomationsAutomationIdActivityRoute: typeof AuthenticatedAutomationsAutomationIdActivityRoute
  AuthenticatedAutomationsAutomationIdContentRoute: typeof AuthenticatedAutomationsAutomationIdContentRoute
  AuthenticatedAutomationsAutomationIdDirectMessageRoute: typeof AuthenticatedAutomationsAutomationIdDirectMessageRoute
  AuthenticatedAutomationsAutomationIdFinalActionRoute: typeof AuthenticatedAutomationsAutomationIdFinalActionRoute
  AuthenticatedAutomationsAutomationIdIdentificationRoute: typeof AuthenticatedAutomationsAutomationIdIdentificationRoute
  AuthenticatedAutomationsAutomationIdKeywordRoute: typeof AuthenticatedAutomationsAutomationIdKeywordRoute
  AuthenticatedAutomationsAutomationIdPublicReplyRoute: typeof AuthenticatedAutomationsAutomationIdPublicReplyRoute
  AuthenticatedAutomationsAutomationIdReviewRoute: typeof AuthenticatedAutomationsAutomationIdReviewRoute
  AuthenticatedAutomationsAutomationIdTestRoute: typeof AuthenticatedAutomationsAutomationIdTestRoute
  AuthenticatedAutomationsAutomationIdIndexRoute: typeof AuthenticatedAutomationsAutomationIdIndexRoute
}

const AuthenticatedAutomationsAutomationIdRouteRouteChildren: AuthenticatedAutomationsAutomationIdRouteRouteChildren =
  {
    AuthenticatedAutomationsAutomationIdActivityRoute:
      AuthenticatedAutomationsAutomationIdActivityRoute,
    AuthenticatedAutomationsAutomationIdContentRoute:
      AuthenticatedAutomationsAutomationIdContentRoute,
    AuthenticatedAutomationsAutomationIdDirectMessageRoute:
      AuthenticatedAutomationsAutomationIdDirectMessageRoute,
    AuthenticatedAutomationsAutomationIdFinalActionRoute:
      AuthenticatedAutomationsAutomationIdFinalActionRoute,
    AuthenticatedAutomationsAutomationIdIdentificationRoute:
      AuthenticatedAutomationsAutomationIdIdentificationRoute,
    AuthenticatedAutomationsAutomationIdKeywordRoute:
      AuthenticatedAutomationsAutomationIdKeywordRoute,
    AuthenticatedAutomationsAutomationIdPublicReplyRoute:
      AuthenticatedAutomationsAutomationIdPublicReplyRoute,
    AuthenticatedAutomationsAutomationIdReviewRoute:
      AuthenticatedAutomationsAutomationIdReviewRoute,
    AuthenticatedAutomationsAutomationIdTestRoute:
      AuthenticatedAutomationsAutomationIdTestRoute,
    AuthenticatedAutomationsAutomationIdIndexRoute:
      AuthenticatedAutomationsAutomationIdIndexRoute,
  }

const AuthenticatedAutomationsAutomationIdRouteRouteWithChildren =
  AuthenticatedAutomationsAutomationIdRouteRoute._addFileChildren(
    AuthenticatedAutomationsAutomationIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedAutomationsAutomationIdRouteRoute: typeof AuthenticatedAutomationsAutomationIdRouteRouteWithChildren
  AuthenticatedConversationsConversationIdRoute: typeof AuthenticatedConversationsConversationIdRoute
  AuthenticatedAutomationsIndexRoute: typeof AuthenticatedAutomationsIndexRoute
  AuthenticatedConversationsIndexRoute: typeof AuthenticatedConversationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedAutomationsAutomationIdRouteRoute:
    AuthenticatedAutomationsAutomationIdRouteRouteWithChildren,
  AuthenticatedConversationsConversationIdRoute:
    AuthenticatedConversationsConversationIdRoute,
  AuthenticatedAutomationsIndexRoute: AuthenticatedAutomationsIndexRoute,
  AuthenticatedConversationsIndexRoute: AuthenticatedConversationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
